version: "3"

services:
  server:
    container_name: interop-server
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    environment: # override the variables from the .env file
      - ENVIRONMENT=local  
      - PORT=4000
    command: npm run dev
    volumes:
      - ./apps/server:/server/
      - /server/node_modules
    ports:
      - 4000:4000


  web-client:
    container_name: interop-web-client
    build: 
      context: ./apps/issuer
      dockerfile: Dockerfile.dev
    restart: on-failure  
    command: npm start
    depends_on: 
      - server
    environment:
      - NODE_ENV=dev   
      - REACT_APP_ENVIRONMENT=local  
      - CI=true 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./apps/issuer:/web/
      - /web/node_modules  
    ports:
      - 3000:3000
      - 35729:35729 # websocket for warm-reload


  wallet-client:
    container_name: interop-wallet-client
    build: 
      context: ./apps/wallet
      dockerfile: Dockerfile.dev
    restart: on-failure 
    command: expo start --tunnel  
    volumes:
      - ./apps/wallet:/wallet/
      - /wallet/node_modules       
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0   
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002