FROM node:12

WORKDIR /apps
COPY ./apps/server/package.json /apps/server/
COPY ./apps/server /apps/server/

WORKDIR /apps/server
RUN npm install --silent

# build the server and issuer apps
RUN npm run build && npm test
