version: "3"

services:
  # Run test
  # tests:
  #   container_name: tests
  #   build: 
  #     context: ./apps/server
  #     dockerfile: Dockerfile.dev
  #   env_file: .env
  #   environment: # override the variables from the .env file
  #     - ENVIRONMENT=test  
  #     - PORT=3000
  #   command: npm test
  #   volumes:
  #     - ./apps/server:/server/
  #     - /server/node_modules
  #   ports:
  #     - 3000:3000 

  # Interop Server 
  server:
    container_name: interop-server
    build: 
      context: ./apps/server
      dockerfile: Dockerfile.dev
    env_file: .env
    environment: # override the variables from the .env file
      - ENVIRONMENT=docker  
      - PORT=3000
    command: npm run dev
    volumes:
      - ./apps/server:/server/
      - /server/node_modules
    ports:
      - 3000:3000


  # Web Client 
  web-client:
    container_name: interop-web-client
    build: 
      context: ./apps/issuer
      dockerfile: Dockerfile.dev
    restart: on-failure  
    command: npm run start:dev
    depends_on: 
      - server
    environment:
      - NODE_ENV=dev  
      - CI=true  
      - REACT_APP_ENVIRONMENT=docker  
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./apps/issuer:/web/
      - /web/node_modules  
    ports:
      - 3001:3001
      - 35729:35729 # websocket for warm-reload

  # Wallet Client with hot re-load
  wallet-client:
    container_name: interop-wallet-client
    build: 
      context: ./apps/wallet
      dockerfile: Dockerfile.dev
    restart: on-failure 
    command: expo start --tunnel  
    volumes:
      - ./apps/wallet:/wallet/
      - /wallet/node_modules       
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0   
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002