# Build the Demo Web Client
FROM node:12 AS client-build

WORKDIR /web
COPY ./apps/issuer/package*.json ./
RUN npm install --silent
COPY ./apps/issuer .

RUN npm run build


# Build the server, and serve the web client statically
FROM node:12

WORKDIR /apps
COPY ./apps/server/package*.json /apps/server/
COPY ./apps/server /apps/server/
COPY --from=client-build /web /apps/issuer/

WORKDIR /apps/server
RUN npm install --silent
RUN npm run build

EXPOSE 4000
