on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: CodeClimate Workflow
jobs:
  codeClimateTrigger:
    name: CodeClimate Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name:  Download cc-test-reporter
        run: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter

      - name:  Install dependencies
        run: npm ci && npm run bootstrap

      - name:  Check licenses
        run: npm run checkLicenses

      - name:  Build
        run: npm run build                

      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          ENVIRONMENT: ${{secrets.ENVIRONMENT}}
          ENCRYPTED_SEED: ${{secrets.ENCRYPTED_SEED}}
          PASSWORD: ${{secrets.PASSWORD}}
          HOST: localhost
          REVOCATION_LIST_LENGTH: 1
        with:
          coverageCommand: npm run test:coverage:codeclimate

      - name:  Generate and Upload Test Coverage
        run: |
            $GITHUB_WORKSPACE/tmp/cc-test-reporter sum-coverage $GITHUB_WORKSPACE/tmp/codeclimate.*.json -p $(ls -1q $GITHUB_WORKSPACE/tmp/codeclimate.*.json | wc -l) -d -o tmp/codeclimate.total.json
            $GITHUB_WORKSPACE/tmp/cc-test-reporter upload-coverage -i $GITHUB_WORKSPACE/tmp/codeclimate.total.json
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          ENVIRONMENT: ${{secrets.ENVIRONMENT}}
          ENCRYPTED_SEED: ${{secrets.ENCRYPTED_SEED}}
          PASSWORD: ${{secrets.PASSWORD}}
