on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: CodeClimate Workflow
jobs:
  codeClimateTrigger:
    name: CodeClimate Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name:  Download cc-test-reporter
        run: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter

      - name:  Install dependencies
        run: touch ~/.npmrc && printf "@affinityproject:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN\nunsafe-perm=true" > ~/.npmrc && npm ci && npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name:  Check licenses
        run: npm run checkLicenses

      - name:  Build
        run: npm run build
        env:
          INTEROP_SECRETS: ${{secrets.INTEROP_SECRETS}}                   

      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          INTEROP_SECRETS: ${{secrets.INTEROP_SECRETS}}
          HOST: localhost
          REVOCATION_LIST_LENGTH: 1
        with:
          coverageCommand: npm run test:coverage:codeclimate

      - name:  Generate and Upload Test Coverage
        run: |
            $GITHUB_WORKSPACE/tmp/cc-test-reporter sum-coverage $GITHUB_WORKSPACE/tmp/codeclimate.*.json -p $(ls -1q $GITHUB_WORKSPACE/tmp/codeclimate.*.json | wc -l) -d -o tmp/codeclimate.total.json
            $GITHUB_WORKSPACE/tmp/cc-test-reporter upload-coverage -i $GITHUB_WORKSPACE/tmp/codeclimate.total.json
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
