name: Pull request validation

on:
  pull_request:
    branches:
      - master

jobs:
  licenseCheck:
    name: License Check
    runs-on: ubuntu-latest
    steps:

      - uses:  actions/checkout@v1

      - uses:  actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@affinityproject'

      - name:  Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name:  Run license checker
        run: npm run checkLicenses

  lint_test:
    name: Lint/test
    runs-on: ubuntu-latest
    steps:

      - uses:  actions/checkout@v1

      - uses:  actions/setup-node@v1
        with:
          node-version: 12

      - name:  Install dependencies
        run: touch ~/.npmrc && printf "@affinityproject:registry=https://npm.pkg.github.com\n//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN\nunsafe-perm=true" > ~/.npmrc && npm ci && npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

      - name:  Run linter
        run: npm run lint

      - name:  Generate routes and swagger
        run: cd apps/server && npm run tsoa:routes && npm run tsoa:swagger
        env:
          INTEROP_SECRETS: ${{secrets.INTEROP_SECRETS}}            

      - name:  Run Tests
        run: cd apps/server && ENVIRONMENT=dev npm run test
        env:
          INTEROP_SECRETS: ${{secrets.INTEROP_SECRETS}}        
